# Generated by Django 5.1.3 on 2024-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('int_phone', models.CharField(max_length=256)),
                ('out_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('fax', models.CharField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
